language: ruby

rvm:
  - 2.3.1
  - 2.5.1

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

cache: bundler

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS brillo_test;" -uroot

script:
  - bundle exec rspec
  - cd example_app; bundle exec rspec
